inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
  TargetRubyVersion: 2.2

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

